const problems = [
  {
    contestId: 1903,
    index: 'A',
    name: 'Halloumi Boxes',
    link: 'https://codeforces.com/problemset/problem/1903/A',
    rating: 800,
    week: 1,
    editorial: 'https://youtu.be/VERwZB9H9OU',
  },
  {
    contestId: 1901,
    index: 'A',
    name: 'Line Trip',
    link: 'https://codeforces.com/problemset/problem/1901/A',
    rating: 800,
    week: 1,
    editorial: 'https://youtu.be/c_vIRWMgrps',
  },
  {
    contestId: 1900,
    index: 'A',
    name: 'Cover in Water',
    link: 'https://codeforces.com/problemset/problem/1900/A',
    rating: 800,
    week: 1,
    editorial: 'https://youtu.be/fTePLBuZdzU',
  },
  {
    contestId: 1904,
    index: 'A',
    name: 'Forked',
    link: 'https://codeforces.com/problemset/problem/1904/A',
    rating: 900,
    week: 1,
    editorial: 'https://youtu.be/VERwZB9H9OU',
  },
  {
    contestId: 1883,
    index: 'B',
    name: 'Chemistry',
    link: 'https://codeforces.com/problemset/problem/1883/B',
    rating: 900,
    week: 1,
    editorial: 'https://youtu.be/ik2W326zOug',
  },
  {
    contestId: 1878,
    index: 'C',
    name: 'Vasilije in Cack',
    link: 'https://codeforces.com/problemset/problem/1878/C',
    rating: 900,
    week: 1,
    editorial: 'https://youtu.be/VERwZB9H9OU',
  },
  {
    contestId: 1913,
    index: 'B',
    name: 'Swap and Delete',
    link: 'https://codeforces.com/problemset/problem/1913/B',
    rating: 1000,
    week: 1,
  },
  {
    contestId: 1883,
    index: 'C',
    name: 'Raspberries',
    link: 'https://codeforces.com/problemset/problem/1883/C',
    rating: 1000,
    week: 1,
    editorial: 'https://youtu.be/8VfJ_8EXnNs',
  },
  {
    contestId: 1876,
    index: 'A',
    name: 'Helmets in Night Light',
    link: 'https://codeforces.com/problemset/problem/1876/A',
    rating: 1000,
    week: 1,
    editorial: 'https://youtu.be/0QbxdOYYKR8',
  },
  {
    contestId: 1917,
    index: 'B',
    name: 'Erase First or Second Letter',
    link: 'https://codeforces.com/problemset/problem/1917/B',
    rating: 1100,
    week: 1,
  },
  {
    contestId: 1914,
    index: 'C',
    name: 'Quests',
    link: 'https://codeforces.com/problemset/problem/1914/C',
    rating: 1100,
    week: 1,
  },
  {
    contestId: 1904,
    index: 'B',
    name: 'Collecting Game',
    link: 'https://codeforces.com/problemset/problem/1904/B',
    rating: 1100,
    week: 1,
    editorial: 'https://youtu.be/kjuTeWKWhP0',
  },
  {
    contestId: 1914,
    index: 'D',
    name: 'Three Activities',
    link: 'https://codeforces.com/problemset/problem/1914/D',
    rating: 1200,
    week: 1,
  },
  {
    contestId: 1909,
    index: 'B',
    name: 'Make Almost Equal With Mod',
    link: 'https://codeforces.com/problemset/problem/1909/B',
    rating: 1200,
    week: 1,
    editorial: 'https://youtu.be/iJVN9NVOivc',
  },
  {
    contestId: 1872,
    index: 'D',
    name: 'Plus Minus Permutation',
    link: 'https://codeforces.com/problemset/problem/1872/D',
    rating: 1200,
    week: 1,
    editorial: 'https://youtu.be/M4IKSJwjUxU',
  },
  {
    contestId: 1899,
    index: 'A',
    name: 'Game with Integers',
    link: 'https://codeforces.com/problemset/problem/1899/A',
    rating: 800,
    week: 2,
    editorial: 'https://youtu.be/B8EdtANZ7JA',
  },
  {
    contestId: 1896,
    index: 'A',
    name: 'Jagged Swaps',
    link: 'https://codeforces.com/problemset/problem/1896/A',
    rating: 800,
    week: 2,
    editorial: 'https://youtu.be/LCYx3jnpwXM',
  },
  {
    contestId: 1890,
    index: 'A',
    name: "Doremy's Paint 3",
    link: 'https://codeforces.com/problemset/problem/1890/A',
    rating: 800,
    week: 2,
    editorial: 'https://youtu.be/0kC8c5UKShY',
  },
  {
    contestId: 1875,
    index: 'A',
    name: 'Jellyfish and Undertale',
    link: 'https://codeforces.com/problemset/problem/1875/A',
    rating: 900,
    week: 2,
    editorial: 'https://youtu.be/JLG6pE4YaSU',
  },
  {
    contestId: 1869,
    index: 'A',
    name: 'Make It Zero',
    link: 'https://codeforces.com/problemset/problem/1869/A',
    rating: 900,
    week: 2,
    editorial: 'https://youtu.be/MYzXO_hE0OY',
  },
  {
    contestId: 1855,
    index: 'B',
    name: 'Longest Divisors Interval',
    link: 'https://codeforces.com/problemset/problem/1855/B',
    rating: 900,
    week: 2,
    editorial: 'https://youtu.be/Emio20R4qOo',
  },
  {
    contestId: 1859,
    index: 'B',
    name: 'Olya and Game with Arrays',
    link: 'https://codeforces.com/problemset/problem/1859/B',
    rating: 1000,
    week: 2,
  },
  {
    contestId: 1849,
    index: 'B',
    name: 'Monsters',
    link: 'https://codeforces.com/problemset/problem/1849/B',
    rating: 1000,
    week: 2,
  },
  {
    contestId: 1840,
    index: 'C',
    name: 'Ski Resort',
    link: 'https://codeforces.com/problemset/problem/1840/C',
    rating: 1000,
    week: 2,
  },
  {
    contestId: 1899,
    index: 'C',
    name: 'Yarik and Array',
    link: 'https://codeforces.com/problemset/problem/1899/C',
    rating: 1100,
    week: 2,
  },
  {
    contestId: 1899,
    index: 'B',
    name: '250 Thousand Tons of TNT',
    link: 'https://codeforces.com/problemset/problem/1899/B',
    rating: 1100,
    week: 2,
  },
  {
    contestId: 1891,
    index: 'B',
    name: 'déjà vu',
    link: 'https://codeforces.com/problemset/problem/1891/B',
    rating: 1100,
    week: 2,
  },
  {
    contestId: 1857,
    index: 'C',
    name: 'Assembly via Minimums',
    link: 'https://codeforces.com/problemset/problem/1857/C',
    rating: 1200,
    week: 2,
    editorial: 'https://youtu.be/M6lE8jg-hBI',
  },
  {
    contestId: 1848,
    index: 'B',
    name: 'Vika and the Bridge',
    link: 'https://codeforces.com/problemset/problem/1848/B',
    rating: 1200,
    week: 2,
  },
  {
    contestId: 1832,
    index: 'C',
    name: 'Contrast Value',
    link: 'https://codeforces.com/problemset/problem/1832/C',
    rating: 1200,
    week: 2,
  },
  {
    contestId: 1881,
    index: 'A',
    name: "Don't Try to Count",
    link: 'https://codeforces.com/problemset/problem/1881/A',
    rating: 800,
    week: 3,
    editorial: 'https://youtu.be/vEahrgeHwKc',
  },
  {
    contestId: 1878,
    index: 'A',
    name: 'How Much Does Daytona Cost',
    link: 'https://codeforces.com/problemset/problem/1878/A',
    rating: 800,
    week: 3,
    editorial: 'https://youtu.be/N2WJZ2dGmLk',
  },
  {
    contestId: 1877,
    index: 'A',
    name: 'Goals of Victory',
    link: 'https://codeforces.com/problemset/problem/1877/A',
    rating: 800,
    week: 3,
  },
  {
    contestId: 1850,
    index: 'D',
    name: 'Balanced Round',
    link: 'https://codeforces.com/problemset/problem/1850/D',
    rating: 900,
    week: 3,
  },
  {
    contestId: 1837,
    index: 'B',
    name: 'Comparison String',
    link: 'https://codeforces.com/problemset/problem/1837/B',
    rating: 900,
    week: 3,
    editorial: 'https://youtu.be/lO0wSSpPNIc',
  },
  {
    contestId: 1828,
    index: 'B',
    name: 'Permutation Swap',
    link: 'https://codeforces.com/problemset/problem/1828/B',
    rating: 900,
    week: 3,
    editorial: 'https://youtu.be/1RlQjBh9qiw',
  },
  {
    contestId: 1831,
    index: 'B',
    name: 'Array Merging',
    link: 'https://codeforces.com/problemset/problem/1831/B',
    rating: 1000,
    week: 3,
  },
  {
    contestId: 1791,
    index: 'D',
    name: 'Distinct Split',
    link: 'https://codeforces.com/problemset/problem/1791/D',
    rating: 1000,
    week: 3,
  },
  {
    contestId: 1765,
    index: 'M',
    name: 'Minimum LCM',
    link: 'https://codeforces.com/problemset/problem/1765/M',
    rating: 1000,
    week: 3,
  },
  {
    contestId: 1873,
    index: 'E',
    name: 'Building an Aquarium',
    link: 'https://codeforces.com/problemset/problem/1873/E',
    rating: 1100,
    week: 3,
    editorial: 'https://youtu.be/wdWkYN9cevY',
  },
  {
    contestId: 1869,
    index: 'B',
    name: '2D Travelling',
    link: 'https://codeforces.com/problemset/problem/1869/B',
    rating: 1100,
    week: 3,
    editorial: 'https://youtu.be/UStXhAH9_Cc',
  },
  {
    contestId: 1850,
    index: 'E',
    name: 'Cardboard for picture',
    link: 'https://codeforces.com/problemset/problem/1850/E',
    rating: 1100,
    week: 3,
  },
  {
    contestId: 1808,
    index: 'B',
    name: 'Playing in a Casino',
    link: 'https://codeforces.com/problemset/problem/1808/B',
    rating: 1200,
    week: 3,
    editorial: 'https://youtu.be/b0ZuLvNuvY4',
  },
  {
    contestId: 1793,
    index: 'C',
    name: 'Dora and Search',
    link: 'https://codeforces.com/problemset/problem/1793/C',
    rating: 1200,
    week: 3,
    editorial: 'https://youtu.be/6XzG6OSAeko',
  },
  {
    contestId: 1790,
    index: 'D',
    name: 'Matryoshkas',
    link: 'https://codeforces.com/problemset/problem/1790/D',
    rating: 1200,
    week: 3,
    editorial: 'https://youtu.be/mRu-7kUl764',
  },
  {
    contestId: 1873,
    index: 'C',
    name: ' Target Practice',
    link: 'https://codeforces.com/problemset/problem/1873/C',
    rating: 800,
    week: 4,
    editorial: 'https://youtu.be/EG0dJDyZ0zU',
  },
  {
    contestId: 1866,
    index: 'A',
    name: 'Ambitious Kid',
    link: 'https://codeforces.com/problemset/problem/1866/A',
    rating: 800,
    week: 4,
  },
  {
    contestId: 1862,
    index: 'B',
    name: 'Sequence Game',
    link: 'https://codeforces.com/problemset/problem/1862/B',
    rating: 800,
    week: 4,
    editorial: 'https://youtu.be/VP1oLpMYHBE',
  },
  {
    contestId: 1807,
    index: 'D',
    name: 'Odd Queries',
    link: 'https://codeforces.com/problemset/problem/1807/D',
    rating: 900,
    week: 4,
  },
  {
    contestId: 1794,
    index: 'B',
    name: 'Not Dividing',
    link: 'https://codeforces.com/problemset/problem/1794/B',
    rating: 900,
    week: 4,
  },
  {
    contestId: 1726,
    index: 'A',
    name: 'Mainak and Array',
    link: 'https://codeforces.com/problemset/problem/1726/A',
    rating: 900,
    week: 4,
  },
  {
    contestId: 1744,
    index: 'C',
    name: 'Traffic Light',
    link: 'https://codeforces.com/problemset/problem/1744/C',
    rating: 1000,
    week: 4,
  },
  {
    contestId: 1725,
    index: 'B',
    name: 'Basketball Together',
    link: 'https://codeforces.com/problemset/problem/1725/B',
    rating: 1000,
    week: 4,
  },
  {
    contestId: 1715,
    index: 'B',
    name: 'Beautiful Array',
    link: 'https://codeforces.com/problemset/problem/1715/B',
    rating: 1000,
    week: 4,
  },
  {
    contestId: 1842,
    index: 'B',
    name: 'Tenzing and Books',
    link: 'https://codeforces.com/problemset/problem/1842/B',
    rating: 1100,
    week: 4,
  },
  {
    contestId: 1832,
    index: 'B',
    name: 'Maximum Sum',
    link: 'https://codeforces.com/problemset/problem/1832/B',
    rating: 1100,
    week: 4,
  },
  {
    contestId: 1827,
    index: 'A',
    name: 'Counting Orders',
    link: 'https://codeforces.com/problemset/problem/1827/A',
    rating: 1100,
    week: 4,
    editorial: 'https://youtu.be/zhAJj_EIV20',
  },
  {
    contestId: 1742,
    index: 'E',
    name: 'Scuza',
    link: 'https://codeforces.com/problemset/problem/1742/E',
    rating: 1200,
    week: 4,
  },
  {
    contestId: 1734,
    index: 'C',
    name: 'Removing Smallest Multiples',
    link: 'https://codeforces.com/problemset/problem/1734/C',
    rating: 1200,
    week: 4,
    editorial: 'https://youtu.be/lFA94rETRp8',
  },
  {
    contestId: 1729,
    index: 'D',
    name: 'Friends and the Restaurants',
    link: 'https://codeforces.com/problemset/problem/1729/D',
    rating: 1200,
    week: 4,
    editorial: 'https://youtu.be/tYQa68sEmfw',
  },
  {
    contestId: 1859,
    index: 'A',
    name: 'United We Stand',
    link: 'https://codeforces.com/problemset/problem/1859/A',
    rating: 800,
    week: 5,
  },
  {
    contestId: 1858,
    index: 'A',
    name: 'Buttons',
    link: 'https://codeforces.com/problemset/problem/1858/A',
    rating: 800,
    week: 5,
  },
  {
    contestId: 1857,
    index: 'A',
    name: 'Array Colouring',
    link: 'https://codeforces.com/problemset/problem/1857/A',
    rating: 800,
    week: 5,
    editorial: 'https://youtu.be/uuTf0a37hYU',
  },
  {
    contestId: 1696,
    index: 'B',
    name: 'NIT Destroys the Universe',
    link: 'https://codeforces.com/problemset/problem/1696/B',
    rating: 900,
    week: 5,
  },
  {
    contestId: 1679,
    index: 'A',
    name: 'AvtoBus',
    link: 'https://codeforces.com/problemset/problem/1679/A',
    rating: 900,
    week: 5,
  },
  {
    contestId: 1675,
    index: 'B',
    name: 'Make it Increasing',
    link: 'https://codeforces.com/problemset/problem/1675/B',
    rating: 900,
    week: 5,
  },
  {
    contestId: 1704,
    index: 'B',
    name: 'Luke is a Foodie',
    link: 'https://codeforces.com/problemset/problem/1704/B',
    rating: 1000,
    week: 5,
  },
  {
    contestId: 1691,
    index: 'B',
    name: 'Shoe Shuffling',
    link: 'https://codeforces.com/problemset/problem/1691/B',
    rating: 1000,
    week: 5,
  },
  {
    contestId: 1690,
    index: 'D',
    name: 'Black and White Stripe',
    link: 'https://codeforces.com/problemset/problem/1690/D',
    rating: 1000,
    week: 5,
  },
  {
    contestId: 1826,
    index: 'B',
    name: 'Lunatic Never  Content',
    link: 'https://codeforces.com/problemset/problem/1826/B',
    rating: 1100,
    week: 5,
    editorial: 'https://youtu.be/_bugs5E6q4I',
  },
  {
    contestId: 1821,
    index: 'B',
    name: 'Sort the Subarray',
    link: 'https://codeforces.com/problemset/problem/1821/B',
    rating: 1100,
    week: 5,
    editorial: 'https://youtu.be/XBhc5PMXOas',
  },
  {
    contestId: 1820,
    index: 'B',
    name: "JoJo's Incredible Adventures",
    link: 'https://codeforces.com/problemset/problem/1820/B',
    rating: 1100,
    week: 5,
  },
  {
    contestId: 1704,
    index: 'C',
    name: 'Virus',
    link: 'https://codeforces.com/problemset/problem/1704/C',
    rating: 1200,
    week: 5,
  },
  {
    contestId: 1703,
    index: 'E',
    name: 'Mirror Grid',
    link: 'https://codeforces.com/problemset/problem/1703/E',
    rating: 1200,
    week: 5,
  },
  {
    contestId: 1692,
    index: 'E',
    name: 'Binary Dequeue',
    link: 'https://codeforces.com/problemset/problem/1692/E',
    rating: 1200,
    week: 5,
    editorial: 'https://youtu.be/erEgJ7uTzAU',
  },
];

export default problems;
